id: IB9B94663
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:53:57+00:00'
last_modified: '2022-06-08T06:16:17.221154+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03809
  title: རྨ་ལྷོའི་དེབ་ཐེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    054D:
      image_group_id: I1PD90075
      title: ''
      total_pages: 852
      order: 1
      base_file: 054D.txt
    9F09:
      image_group_id: I1PD90076
      title: ''
      total_pages: 890
      order: 2
      base_file: 9F09.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
