id: IB9B94663
legacy_id: P006704
ocr_import_info:
  bdrc_scan_id: W00KG03809
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:51:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:11:54.165061+00:00'
last_modified: 2022-08-29 20:14:23.661700
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03809
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03809
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: 黄南 藏族 自治州志
statistics:
  ocr_word_mean_confidence_index: 0.9439257235623616
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD90076:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD90076
      total_pages: 890
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD90076.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9506008576625767
    legacy_id: v002
  I1PD90075:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD90075
      total_pages: 852
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD90075.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9377086173719901
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
